# backend/pyproject.toml
[tool.poetry]
name = "ha-backend"
version = "0.1.0"
description = "AI Attendance Backend"
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "src", from = "."}]

[tool.poetry.dependencies]
python = "^3.13"
fastapi = "^0.104.1"
uvicorn = {extras = ["standard"], version = "^0.24.0"}
motor = "^3.7.1"
pymongo = "^4.15.5"
python-dotenv = "^1.2.1"
pydantic = "^2.12.5"
email-validator = "^2.3.0"
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
python-jose = {extras = ["cryptography"], version = "^3.5.0"}
python-multipart = "^0.0.21"
authlib = "^1.6.6"
httpx = "^0.28.1"
itsdangerous = "^2.2.0"
bcrypt = "4.0.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.4"
pytest-asyncio = "^0.21.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
